---
- name: Prepare directories on the remote server
  become: true
  ansible.builtin.file:
    path: "{{ config_root }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - "{{ role_name }}"
    - "{{ role_name }}/src"

- name: Copy docker-compose.yml file to deploy Gitlab server
  become: true
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ config_root }}/{{ role_name }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
