---
- name: Check current docker-compose version.
  ansible.builtin.command: "{{ packages_docker_compose_path }} --version"
  register: packages_docker_compose_vsn
  check_mode: false
  changed_when: false
  failed_when: false

- name: Set current docker-compose version.
  ansible.builtin.set_fact:
      packages_docker_compose_current_version: "{{ packages_docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
  when: >
      packages_docker_compose_vsn.stdout is defined
      and (packages_docker_compose_vsn.stdout | length > 0)

- name: Delete existing docker-compose version if it's different.
  ansible.builtin.file:
      path: "{{ packages_docker_compose_path }}"
      state: absent
  when: >
      packages_docker_compose_current_version is defined
      and (packages_docker_compose_version | regex_replace('v', '')) not in packages_docker_compose_current_version

- name: Install Docker Compose (if configured).
  ansible.builtin.get_url:
      url: "{{ packages_docker_compose_url }}"
      dest: "{{ packages_docker_compose_path }}"
      mode: "0755"
  when: >
      (packages_docker_compose_current_version is not defined)
      or (packages_docker_compose_current_version | length == 0)
      or (packages_docker_compose_current_version is version((packages_docker_compose_version | regex_replace('v', '')), '<'))
