---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
      name: "{{ packages_docker_obsolete_packages }}"
      state: absent

- name: Install gnupg2
  ansible.builtin.package:
      name: gnupg2
      state: present

- name: Add Docker GPG key.
  ansible.builtin.rpm_key:
      key: "{{ packages_docker_yum_gpg_key }}"
      state: present
  when: packages_docker_add_repo | bool

- name: Add Docker repository.
  ansible.builtin.get_url:
      url: "{{ packages_docker_yum_repo_url }}"
      dest: "/etc/yum.repos.d/docker-{{ packages_docker_edition }}.repo"
      owner: root
      group: root
      mode: "0644"
  when: packages_docker_add_repo | bool

- name: Configure Docker Nightly repo.
  community.general.ini_file:
      dest: "/etc/yum.repos.d/docker-{{ packages_docker_edition }}.repo"
      section: "docker-{{ packages_docker_edition }}-nightly"
      option: enabled
      value: "{{ packages_docker_yum_repo_enable_nightly }}"
      mode: "0644"
      no_extra_spaces: true
  when: packages_docker_add_repo | bool

- name: Configure Docker Test repo.
  community.general.ini_file:
      dest: "/etc/yum.repos.d/docker-{{ packages_docker_edition }}.repo"
      section: "docker-{{ packages_docker_edition }}-test"
      option: enabled
      value: "{{ packages_docker_yum_repo_enable_test }}"
      mode: "0644"
      no_extra_spaces: true
  when: packages_docker_add_repo | bool

- name: Configure containerd on RHEL 8.
  when: ansible_distribution_major_version | int == 8
  block:
      - name: Ensure runc is not installed.
        ansible.builtin.package:
            name: runc
            state: absent

      - name: Ensure container-selinux is installed.
        ansible.builtin.package:
            name: container-selinux
            state: present

      - name: Ensure containerd.io is installed.
        ansible.builtin.package:
            name: containerd.io
            state: present
