---
driver:
  name: podman

dependency:
  name: galaxy

platforms:
  - name: centos
    image: docker.io/geerlingguy/docker-centos8-ansible
    pre_build_image: true
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
  - name: debian
    image: docker.io/geerlingguy/docker-debian12-ansible
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    host_vars:
      ubuntu:
        packages:
          - htop
          - podman
          - podman-compose
      debian:
        packages:
          - htop
          - tmux
      centos:
        packages:
          - htop
          - tmux
          - podman
          - podman-compose

verifier:
  name: testinfra
  options:
    sudo: true
