---
galaxy_info:
    author: riggidal
    license: MIT
    min_ansible_version: "2.9"
    platforms:
        - name: Ubuntu
          versions:
              - bionic
              - focal
        - name: Debian
          versions:
              - buster
        - name: EL
          versions:
              - "7"
              - "8"
    galaxy_tags:
        - firewall
        - iptables
        - security

dependencies: []
