---
galaxy_info:
  author: aki
  description: your role description
  company: pepesugar

  license: GPL-3.0-only

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
    - name: EL
      versions:
        - "7"
        - "8"

  galaxy_tags:
    - time
    - ntp
    - system
dependencies: []
