---
# tasks file for ansible-timedatectl
- name: Setup timesync config
  become: true
  ansible.builtin.template:
    src: timesyncd.conf.template
    dest: /etc/systemd/timesyncd.conf
    mode: "0644"

- name: Set required timezone
  become: true
  ansible.builtin.command: timedatectl set-timezone {{ configure_clocks_timezone }}

- name: Enable NTP synchronization
  become: true
  ansible.builtin.command: timedatectl set-ntp true
