---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
packages_docker_edition: "ce"
packages_docker_packages:
    - "docker-{{ docker_edition }}"
    - "docker-{{ docker_edition }}-cli"
    - "docker-{{ docker_edition }}-rootless-extras"
    - "containerd.io"
    - docker-buildx-plugin
packages_docker_packages_state: present
packages_docker_obsolete_packages:
    - docker
    - docker.io
    - docker-engine
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc

# Service options.
packages_docker_service_manage: true
packages_docker_service_state: started
packages_docker_service_enabled: true
packages_docker_restart_handler_state: restarted

# Docker Compose Plugin options.
packages_docker_install_compose_plugin: true
packages_docker_compose_package: docker-compose-plugin
packages_docker_compose_package_state: present

# Docker Compose options.
packages_docker_install_compose: false
packages_docker_compose_version: "v2.32.1"
packages_docker_compose_arch: "{{ ansible_architecture }}"
packages_docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ docker_compose_arch }}"
packages_docker_compose_path: /usr/local/bin/docker-compose

# Enable repo setup
packages_docker_add_repo: true

# Docker repo URL.
packages_docker_repo_url: https://download.docker.com/linux

# Used only for Debian/Ubuntu/Pop!_OS/Linux Mint. Switch 'stable' to 'nightly' if needed.
packages_docker_apt_release_channel: stable
# docker_apt_ansible_distribution is a workaround for Ubuntu variants which can't be identified as such by Ansible,
# and is only necessary until Docker officially supports them.
packages_docker_apt_ansible_distribution: "{{ 'ubuntu' if ansible_distribution in ['Pop!_OS', 'Linux Mint'] else ansible_distribution }}"
packages_docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'armhf' if ansible_architecture == 'armv7l' else 'amd64' }}"
packages_docker_apt_repository:
    "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }}
    {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
packages_docker_apt_ignore_key_error: true
packages_docker_apt_gpg_key: "{{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }}/gpg"
packages_docker_apt_gpg_key_checksum: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
packages_docker_apt_filename: "docker"

# Used only for RedHat/CentOS/Fedora.
packages_docker_yum_repo_url: "{{ docker_repo_url }}/{{ (ansible_distribution == 'Fedora') | ternary('fedora','centos') }}/docker-{{ docker_edition }}.repo"
packages_docker_yum_repo_enable_nightly: "0"
packages_docker_yum_repo_enable_test: "0"
packages_docker_yum_gpg_key: "{{ docker_repo_url }}/{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'centos') }}/gpg"

# A list of users who will be added to the docker group.
packages_docker_users: []
# Docker daemon options as a dict
packages_docker_daemon_options: {}
