---
- name: Set hostname to match inventory_hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: Edit /etc/hosts so that it contains the hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: "^127\\.0\\.0\\.1"
    line: "127.0.0.1 localhost {{ inventory_hostname }}"
    state: present
    create: true
  become: true
