---
galaxy_info:
  author: DevOps Team
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - certificate
    - ssl

dependencies:
  - role: software/install_certbot
  - role: software/install_docker

