---
galaxy_info:
  author: DevOps Team
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
    - name: RedHat
      versions:
        - "7"
        - "8"
  galaxy_tags:
    - monitoring
    - agents
    - node-exporter

dependencies:
  - role: software/install_docker
  - role: monitoring/deploy_monitoring

