- name: Create user groups
  become: yes
  group:
    name: "{{ item.key }}"
    state: present
  with_dict:
    - "{{ manage_users_global.permissions | default({}, true) }}"

- name: Add sudoers files to allow groups execute some cmds
  become: yes
  copy:
    content: |
      # {{ item.value.description }}
      {{ item.value.content }}
    dest: /etc/sudoers.d/{{ item.key }}
    owner: root
    group: root
    mode: '0440'
  with_dict:
    - "{{ manage_users_global.permissions | default({}, true) }}"
